### ISSUE TITLE
Incorrect version packaged as a Release; "v0.09.2" is actually v0.09.1

### ISSUE THREAD

**Issue by andrewferrier** [boysetsfrog/vimpc#102]
See https://github.com/boysetsfrog/vimpc/archive/refs/tags/v0.09.2.zip and https://github.com/boysetsfrog/vimpc/archive/refs/tags/v0.09.2.tar.gz. Both actually contain v0.09.1, not v0.09.2

**Comment by connermcd** [comment]
Will fix on next release. Just forgot to update version number. Thanks.
