### ISSUE TITLE
error while loading shared libraries: libtag.so.1

### ISSUE THREAD

**Issue by kirasok** [boysetsfrog/vimpc#106]
OS: ArchLinux
vimpc: 0.09.1 [95ad78d112316a1c290a480481fd1f8abf50b59b]

After update to `taglib 2.0-1`, vimpc stopped launching:

```
vimpc: error while loading shared libraries: libtag.so.1: cannot open shared object file: No such file or directory
```

Works again if symlink `libtag.so.1` to `libtag.so.2`

**Comment by sidtronics** [comment]
You need to rebuild packages from the AUR whenever their dependencies get updated to ensure they link against the new versions.

If you use `yay`, you can rebuild a package like this:

```bash
yay -S vimpc-git --rebuild
```
Tip: use `rebuild-detector` to get notified when a package breaks.
