### ISSUE TITLE
Can't connect to MPD 0.18

### ISSUE THREAD

**Issue by ghost** [boysetsfrog/vimpc#32]
I can't connect to MPD using vimpc. Mpc and ncmpcpp can connect without any problem.

Some info:
- up to date Arch Linux 64-bit
- mpd 0.18.5-1
- libmpdclient 2.9-1
- vimpc rev:478d15b896
- MPD_PORT=6600
- MPD_HOST=localhost
- Error Message: `E2: MPD Error: Connection closed by the server`

just after launch:
![2013-12-07-162442_1920x1200_scrot](https://f.cloud.github.com/assets/1457981/1698533/c3026fc4-5f53-11e3-9217-4973f0c04a64.png)

debug-console (screenshot, because i can't find logs):
![2013-12-07-161216_1920x1200_scrot](https://f.cloud.github.com/assets/1457981/1698519/9a57a784-5f52-11e3-9796-a94a8369cf0c.png)
I just launched vimpc, opened debug-console and ran connect localhost 6600

Error message from mpd.log:
`Dec 07 16:46 : buffered_socket: error on client 18: Output buffer is full`

**Comment by matthiasbeyer** [comment]
Helped me as well. Thanks.
