### ISSUE TITLE
scripting capability

### ISSUE THREAD

**Issue by noc7c9** [boysetsfrog/vimpc#34]
Are there any plans to add scripting capabilities? For example via embed python or similar?

A rough example of what I mean being something like a rudimentary lyrics fetcher
```
alias lyrics python GetLyrics()

python << EOF
def GetLyrics():
    import vimpc, lyrics
    song = vimpc.get_playing()
    tab = vimpc.open_new_tab()
    tab.name = 'Lyrics - ' + song.name
    tab.data = lyrics.fetch(song.name)
EOF
```

...or something like that. Would be a pretty hefty addition though, so your call of course.

**Comment by connermcd** [comment]
There is now a lyrics fetcher built in and I don't think scripting capability is in the plans for this project. Thanks for your suggestion!
