### ISSUE TITLE
Unable to use vimpc with just 20k songs

### ISSUE THREAD

**Issue by rafi** [boysetsfrog/vimpc#39]
MPD says "Output buffer is full" in logs. I had to raise max_output_buffer_size to 11264 for it to work. I only have 20k songs, and mpd db file is 10.3M. Increasing the buffer size is a **bad workaround**, and I have much more songs to import into MPD.

The MPD command that causes the problem is: `listallinfo`

Why don't you use the 'listall' command instead, and progressively get info?

MPD's maintainer said he doesn't support the 'listallinfo' command. He also says:
> I recommend not using clients that employ the "listallinfo" command because they break so easily, and may be very expensive if you're on a mobile connection.  imagine every "reconnect" downloads a hundred megabytes...

**Comment by connermcd** [comment]
I don't have 20k songs to test with, but the `listallinfo` command isn't used in the source as far as I can tell. Are you still having this issue?
