### ISSUE TITLE
Adding content from directory view doesn't refresh playlist

### ISSUE THREAD

**Issue by akadaedalus** [boysetsfrog/vimpc#54]
Something happened since the 0.09.1 release (not tagged here but available on Sourceforge as of 2014-03-02).  When adding music from the directory view using "a", the master branch code does not update the current selection to a green color, and does not show the songs in the playlist view.  However, running "mpc" in another terminal I can see all the expected songs were added.

I don't like to use the library view because sometimes I'll have an album that has multiple artists, or sometimes I've got a "favorite" artist that I'd like to listen to in chronological order, and the directory names are prefixed by the release year.  This naming scheme automatically adds them in the right order in the directory tab.

**Comment by connermcd** [comment]
I can't seem to reproduce this with the most current version. It does seem to be a little delayed but it does color it and add it to the playlist on my end. Any suggestions?

**Comment by akadaedalus** [comment]
No, you've done enough.

I'm running Gentoo and it turns out the "overlay" package tree for MPD is so outdated it was still compiling vimpc from the subversion source tree.  https://svn.code.sf.net/p/vimpc/code/trunk/  From what I can tell, it threw me back to versionish 0.07.2.  So I probably just reported an old bug.  I didn't even realize this until your response made me watch the compilation more closely and I saw it was pulling svn, not git.

I'm going to close this issue, but someone probably ought to go retire the SourceForge pages and associated svn repository.  I'll take it up with the overlay maintainers, which are sadly probably not going to fix it.  Gentoo's main package tree does provide version 0.09.1 just fine.
