### ISSUE TITLE
Support the XDG Base Directory specification

### ISSUE THREAD

**Issue by dkasak** [boysetsfrog/vimpc#56]
Instead of writing dotfiles to the home directory, configuration, cache files and data files (if any) should be written in locations according to the [XDG Base Directory](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) specification. This is to prevent clutter in the home directory.

The gist of it is:
- Place config files inside a directory under `$XDG_CONFIG_HOME` (defaults to `~/.config`, if not set)
- Place data files inside a directory under `$XDG_DATA_HOME` (defaults to `~/.local/share`, if not set)
- Place cache files inside a directory under `$XDG_CACHE_HOME` (defaults to `~/.cache`, if not set)

So, for instance, the configuration file could be placed in `$XDG_CONFIG_HOME/vimpc/vimpcrc`. There are some additional things for applications that need system-wide configuration files and such, but I don't think this applies to vimpc.

**Comment by mox-mox** [comment]
Except .vimpcrc are there any other files, that would need to be moved? I believe (without actually knowing), that the other files would be stored according to what is defined in mpd, right?

**Comment by 4drift** [comment]
I wish this would get addressed, and ideally changed to support XDG.

**Comment by pmhl** [comment]
I think that XDG_CONFIG_DIR is not correct, at least it doesnt work in Arch linux! According to the specification in the link above it should be XDG_CONFIG_HOME.
