### ISSUE TITLE
can't build on linux mint debian edition (jessie)

### ISSUE THREAD

**Issue by nilsbecker** [boysetsfrog/vimpc#57]
first, i installed the dependencies listed on github; this wasn't quite enough, i also had to install automake and some libcurl debug package for `./configure` to run successfully. i then use

```
./autogen.sh
./configure --prefix=$HOME --disable-boost --disable-lyrics
```

however, `make` fails with this message

```
src/lyricsfetcher.cpp:23:46: fatal error: boost/algorithm/string/replace.hpp: No such file or directory    
 #include <boost/algorithm/string/replace.hpp>
compilation terminated.
Makefile:882: recipe for target 'src/vimpc-lyricsfetcher.o' failed
```

which looks like the options are not working?

**Comment by connermcd** [comment]
Yeah this is my fault. Boost is currently a dependency but it's a beast so we want to get rid of it. I can fix this this weekend but for now install boost.

**Comment by connermcd** [comment]
Very sorry about that. You should be able to disable lyrics now (and the boost it requires) with the addition of 726538a765d9cb481376e2858e42e7599c320442. I plan to remove the need for boost from lyrics support entirely when I get a chance. I will close this issue when that is done.

**Comment by connermcd** [comment]
Boost was removed from lyrics fetching in 994b4a5
