### ISSUE TITLE
Remembering search position in directory view

### ISSUE THREAD

**Issue by 97-109-107** [boysetsfrog/vimpc#60]
Would it be possible to remember the position in the directory mode?
Ex.
The list looks like:
````
A
B
C
````
The user navigates to 'B' and enters the directory. Then, after pressing left the user is back to the root list but instead of being on the top of the list, the highlight is maintained on the 'B' entry?

Thank you for the great program!

**Comment by connermcd** [comment]
Fixed with 20ca651b8a8d6da048213b168fb8cb09c4341d9f.
