### ISSUE TITLE
Do I really need to find my mpd dir, and remove playlist by hand to write a change?

### ISSUE THREAD

**Issue by dmilith** [boysetsfrog/vimpc#67]
:write / :save playlistname

it's single shot action. After that is there a way to do a :write! playlistname to overwrite current playlist?

**Comment by connermcd** [comment]
It should do that with recent versions

**Comment by dmilith** [comment]
Using 0.09.1 (sha1: b4e9790eaf0a25035ba32c2c98993fd6900a2c42)

I assume that your suggestion is to try with master. Will try and let You know.

**Comment by dennisschagt** [comment]
@dmilith Did you try and did it work?

**Comment by dmilith** [comment]
@dennisschagt Not yet, waiting for a release, I'd need to add whole autotools (perl, autoconf, automake) dependencies to build it from master, didn't have time yet.

**Comment by connermcd** [comment]
Confirmed working. Closing.
