### ISSUE TITLE
terminate called after throwing instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by Danacus** [boysetsfrog/vimpc#89]
Hello

I have noticed that vimpc crashes in a very specific situation with the following error:

```
terminate called after throwing instance of 'std::out_of_range'
what(): vector::_M_range_check: __n (which is 6) >= this->size() (which is 1)
```

Steps to reproduce:
- Open a playlist from the lists tab (playlist must have at least 2 songs, press enter to set this as the current playlist)
- Go to the playlist tab and select a song with index greater than 1 and press enter to play the song
- Now go to the library tab and select a song. Press enter to play the song. This song will now be the only song in the playlist. 
- When pausing that song with the space bar, while the playlist tab is selected, the song pauses, however, some variable named `__n` still refers to the index of the song that was previously in the playlist, which crashes vimpc with the above error saying this value is outside the range of what would presumably be the playlist.

Perhaps the value of that variable doesn't get updated correctly in this situation?

I am currently using vimpc 0.09.1 [f768eaa4c62c0c8763be3691b84a5b5e812d6b22].

**Comment by connermcd** [comment]
Reproducible
