### ISSUE TITLE
.vimpcrc settings have no effect (not read?)

### ISSUE THREAD

**Issue by kevcrumb** [boysetsfrog/vimpc#95]
I'm making vimpc the default music client on [Split Linux'](https://splitlinux.org) Beast desktop environment.

Whatever I configure in `~/.vimpcrc` has no effect. This is on Void Linux with the package installed according to [this template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/vimpc/template).

I cross-checked with other Linux distributions where the exact same file works as expected.

**Comment by connermcd** [comment]
Should be fixed by 41a663ad5ce8af2e7cc5c2c321229a2fa3ae55c0. Are you still having this issue?

**Comment by kevcrumb** [comment]
As fair as I remember it was resolved by moving the file to `~/.config/vimpc/vimpcrc` back then.
